services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
            - mosquitto
            - influxdb
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mosquitto
        restart: always
        ports:
            - '${MQTT_PORT:-1883}:1883'
        volumes:
            - ./.local/mosquitto/config:/mosquitto/config
            - mosquitto-data:/mosquitto/data
        networks:
            - sail
    influxdb:
        image: influxdb:2.7
        container_name: influxdb
        ports:
            - '${INFLUXDB_PORT:-8086}:8086'
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: admin
            DOCKER_INFLUXDB_INIT_PASSWORD: password
            DOCKER_INFLUXDB_INIT_ORG: myorg
            DOCKER_INFLUXDB_INIT_BUCKET: default
        volumes:
            - influxdb-data:/var/lib/influxdb2
        networks:
            - sail
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - '${GRAFANA_PORT:-3000}:3000'
        volumes:
            - grafana-data:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=password
        depends_on:
            - influxdb
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    influxdb-data:
        driver: local
    grafana-data:
        driver: local
    mosquitto-data:
        driver: local
